export const hotels = [
  {
    id: 1,
    name: "Sunset Resort",
    city: "Nainital",
    distance: 3.4,
    price: 1821,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Mount View",
    city: "Nainital",
    distance: 7.6,
    price: 1971,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Sitara Hotel",
    city: "Nainital",
    distance: 1,
    price: 1962,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "5",
  },
  {
    id: 4,
    name: "Hilltop Retreat",
    city: "Nainital",
    distance: 2.3,
    price: 2100,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "2",
  },
  {
    id: 5,
    name: "Lakeside Inn",
    city: "Nainital",
    distance: 0.8,
    price: 2500,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "1.5",
  },
  {
    id: 6,
    name: "Mountain Breeze",
    city: "Nainital",
    distance: 5.1,
    price: 1800,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "1.5",
  },
  {
    id: 7,
    name: "Himalayan View Resort",
    city: "Nainital",
    distance: 6.2,
    price: 2700,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "3.75",
  },
  {
    id: 8,
    name: "Green Valley Stay",
    city: "Nainital",
    distance: 3.0,
    price: 1900,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "2.5",
  },
  {
    id: 9,
    name: "Royal Heritage Hotel",
    city: "Nainital",
    distance: 2.7,
    price: 3200,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "2",
  },
  {
    id: 10,
    name: "Pinewood Residency",
    city: "Nainital",
    distance: 4.5,
    price: 2300,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "3",
  },
  {
    id: 11,
    name: "Cloud 9 Resort",
    city: "Nainital",
    distance: 7.8,
    price: 2800,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "4.2",
  },
  {
    id: 12,
    name: "Blue Orchid Hotel",
    city: "Nainital",
    distance: 1.6,
    price: 2400,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "4.5",
  },
  {
    id: 13,
    name: "Serene Lake Resort",
    city: "Nainital",
    distance: 5.9,
    price: 2600,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "5",
  },
  {
    id: 14,
    name: "Doonscape Residency",
    city: "Dehradun",
    distance: 2.1,
    price: 2100,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "3.8",
  },
  {
    id: 15,
    name: "Valley View Retreat",
    city: "Dehradun",
    distance: 4.3,
    price: 2800,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "4.0",
  },
  {
    id: 16,
    name: "The Himalayan Nest",
    city: "Dehradun",
    distance: 1.7,
    price: 2500,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "3.6",
  },
  {
    id: 17,
    name: "Green Valley Inn",
    city: "Dehradun",
    distance: 3.8,
    price: 2200,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "4.1",
  },
  {
    id: 18,
    name: "Doonga Retreat",
    city: "Dehradun",
    distance: 5.0,
    price: 33000,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "4.7",
  },
  {
    id: 19,
    name: "Serenity Stay",
    city: "Dehradun",
    distance: 2.9,
    price: 32400,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "4.3",
  },
  {
    id: 20,
    name: "Cloud Nine Hotel",
    city: "Dehradun",
    distance: 6.2,
    price: 3200,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "3.9",
  },
  {
    id: 21,
    name: "Pinewood Residency",
    city: "Dehradun",
    distance: 1.5,
    price: 2700,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "4.4",
  },
  {
    id: 22,
    name: "Royal Orchid Stay",
    city: "Dehradun",
    distance: 4.9,
    price: 20000,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "4.6",
  },
  {
    id: 23,
    name: "Doonside Bliss",
    city: "Dehradun",
    distance: 3.0,
    price: 2600,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "3.7",
  },
  {
    id: 24,
    name: "Ganga View Retreat",
    city: "Rishikesh",
    distance: 1.2,
    price: 2200,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "4.0",
  },
  {
    id: 25,
    name: "Divine Resort",
    city: "Rishikesh",
    distance: 2.5,
    price: 3500,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "4.8",
  },
  {
    id: 26,
    name: "Himalayan Hideaway",
    city: "Rishikesh",
    distance: 4.1,
    price: 2800,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "3.9",
  },
  {
    id: 27,
    name: "Riverfront Hotel",
    city: "Rishikesh",
    distance: 0.9,
    price: 2400,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "4.2",
  },
  {
    id: 28,
    name: "Yoga Bliss Retreat",
    city: "Rishikesh",
    distance: 3.7,
    price: 3100,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "4.5",
  },
  {
    id: 29,
    name: "Peaceful Stay Inn",
    city: "Rishikesh",
    distance: 2.0,
    price: 1900,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "3.5",
  },
  {
    id: 30,
    name: "The Riverside Camp",
    city: "Rishikesh",
    distance: 6.5,
    price: 2700,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Resort",
    rating: "4.1",
  },
  {
    id: 31,
    name: "Spiritual Stay",
    city: "Rishikesh",
    distance: 1.8,
    price: 2600,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "3.8",
  },
  {
    id: 32,
    name: "Hill View Residency",
    city: "Rishikesh",
    distance: 5.2,
    price: 2300,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Villa",
    rating: "4.0",
  },
  {
    id: 33,
    name: "Lotus Grand",
    city: "Rishikesh",
    distance: 3.3,
    price: 3000,
    img: "https://www.nainitalcorbetttourism.com/images/hotels/nainital-hotels/the-pavilion-hotel-in-nainital.jpg",
    propertyType: "Hotel",
    rating: "4.6",
  },
];
