// src/data/hotelLocations.js

export const cities = [
  "Nainital",
  "Rishikesh",
  "Dehradun",
  "Mussoorie",
  "Haridwar",
  "Corbett",
  "Almora",
  "Mukteshwar",
  "Uttarkashi",
  "Haldwani",
  "Guptkashi",
  "Kanatal",
  "Joshimath",
  "Dhanaulti",
  "Kausani",
  "Mukteswar",
  "Ranikhet",
  "Lansdowne",
  "Kotdwara",
  "Rudrapur (Uttarakhand)",
  "Barkot",
  "Harsil",
  "Duggal Bittha",
  "Chamoli",
  "Rudraprayag",
  "Roorkee",
  "Ukhimath",
  "Tehri",
  "Phata",
  "Munsyari",
  "Badrinath",
  "Chamba (Uttarakhand)",
  "Chakrata",
  "Sitapur",
  "Auli",
  "Kedarnath",
  "Baniyakund",
  "Pithoragarh",
  "Basan",
  "Gangnani",
  "Kotabagh",
  "Ramgarh",
  "Prem Nagar",
  "Selakui",
  "Champawat",
  "Dhanachuli",
  "Ladfora Talla",
  "Umrakot Urf Baidanu",
  "Kashipur",
  "Pauri",
  "Srinagar (Uttarakhand)",
  "Seraki",
  "Shivpuri",
  "Sama",
  "Kiari Kham",
  "Bohra Kote",
  "Chaukori",
  "Binsar",
  "Bail Parao",
  "Nanakmatta",
  "Pipalkoti",
  "Narendra Nagar",
  "Jhajra",
  "Tanakpur",
  "Belparao",
  "Tota am",
  "Chhoi",
  "Bageshwar",
  "Gauchar",
  "Gounu",
  "Yamunotri",
  "Bhimtal",
  "Pauri Garhwal",
  "Ghangaria",
  "Jalai",
  "Jangalia Gaon Ganja",
  "Dwarahat",
  "Pauvalgarh",
  "Galajwari",
  "Chaubattia",
  "Neripura",
  "Govind Ghat (Uttarakhand)",
  "Sankri",
  "Chham",
  "Jim Corbett",
  "Rani Pokhri",
  "Patkote",
  "Teda",
  "Chilkiya Range",
  "Kanchanpur",
  "Bahadrabad",
  "Gwaldam",
  "Harnagar Jangalia Gaon",
  "Tapovan",
  "Chadarawari",
  "Kalagarh",
  "Gaja",
  "Thamana",
  "Bajpur",
  "Shivlalpur Joshi",
  "Jhultar Barkhet",
  "Syanachatti",
  "Chopra",
  "Pantnagar",
  "Jajal",
  "Bijni",
  "Devaprayag",
  "Dobara",
  "Ghastoli",
  "Syahi Devi Bagich",
  "Brinad",
  "Chhara",
  "Seti Majhgaon",
  "Himmatpur Bailparao",
  "Rama",
  "Bhatrojkhan",
  "Laluri"
];


